 # @license GPL-3.0-or-later
 # Copyright (C) 2025 Caleb Gyamfi - Omnixys Technologies
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 # See the GNU General Public License for more details.
 #
 # For more information, visit <https://www.gnu.org/licenses/>.
 
version: 2
updates:

  # 1. GitHub Actions Updates
  - package-ecosystem: "github-actions"
    directory: "/"               # Root-Verzeichnis des Repos
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
      timezone: "Europe/Berlin"
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "ci"
    reviewers:
      - omnixys-maintainers
    assignees:
      - caleb-script

  # 2. Gradle Runtime Dependencies
  - package-ecosystem: "gradle"
    directory: "/"               # Falls du ein Submodul hast, hier Pfad anpassen
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - gradle
      - runtime
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot-starter-logging"
        versions: [">=3.0.0"]
    commit-message:
      prefix: "fix"
      include: "scope"
    reviewers:
      - omnixys-maintainers
    assignees:
      - caleb-script

  # 3. Gradle Dev/Test Dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "02:00"
      timezone: "Europe/Berlin"
    labels:
      - dependencies
      - gradle
      - dev
    allow:
      - dependency-type: "development"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - omnixys-maintainers
    assignees:
      - caleb-script

