dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - '**/package.json'
          - '**/package-lock.json'
          - '**/pyproject.toml'
          - '**/build.gradle'
          - '**/build.gradle.kts'
          - '**/pom.xml'

github-actions:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/*.yml'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'
          - '.github/**'
          - 'devtools/**'

docs:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'

security:
  - changed-files:
      - any-glob-to-any-file:
          - '**/SECURITY.md'
          - '**/*keycloak*'
          - '**/*auth*'
          - '**/*.pem'
          - '**/*.crt'

frontend:
  - changed-files:
      - any-glob-to-any-file:
          - 'apps/frontend/**'
          - 'src/frontend/**'

backend:
  - changed-files:
      - any-glob-to-any-file:
          - 'apps/backend/**'
          - 'src/backend/**'

feature:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**'
          - 'apps/**'
          - 'features/**'

bug:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.ts'
          - '**/*.java'
          - '**/*.py'

refactor:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*service*'
          - '**/*controller*'
          - '**/*resolver*'
