dependencies:
  - '**/package.json'
  - '**/package-lock.json'
  - '**/pyproject.toml'
  - '**/build.gradle'
  - '**/build.gradle.kts'
  - '**/pom.xml'

github-actions:
  - '.github/workflows/*.yml'

ci:
  - '.github/**'
  - 'devtools/**'

docs:
  - '**/*.md'

frontend:
  - 'src/**'
  - 'apps/frontend/**'

backend:
  - 'apps/backend/**'
