include:
  - path: camunda/compose.yaml
  - path: kafka/compose.yaml
  - path: observability/compose.yaml
    
services:
  authentication:
    container_name: omnixys-authentication
    image: omnixys/authentication-service:latest
    pull_policy: always
    restart: unless-stopped
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:7501/health/readiness || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - type: bind
        source: ./.env
        target: /workspace/.env
      - type: bind
        source: ../../../../keys/certificate.crt
        target: /workspace/certificate.crt
        read_only: true
      - type: bind
        source: ../../../../keys/key.pem
        target: /workspace/key.pem
        read_only: true
    ports:
      - target: 3000
        published: 7501
    depends_on:
      tempo:
        condition: service_healthy
      kafka:
        condition: service_healthy
      keycloak:
        condition: service_healthy