
# ==============================================================================
# N o d e
# ==============================================================================
node:
  port: 7501

# ==============================================================================
# D a t e n b a n k
# ==============================================================================

# "pg-native" erfordert zusaetzlich die lokale Installation von PostgreSQL
# "better-sqlite3" erfordert Python zum Uebersetzen, wenn das Docker-Image gebaut wird



# ==============================================================================
# K A F K A
# ==============================================================================
kafka:
  host: localhost
  
# ==============================================================================
# K e y c l o a k
# ==============================================================================
keycloak:
  authServerUrl: http://localhost:18080/auth
  realm: camunda-platform
  # siehe Keycloak Menuepunkt "Clients" > Tab "Clients list" > Spalte "Client ID"
  clientId: camunda-identity
  #tokenValidation: online

# ==============================================================================
# L o g g i n g
# ==============================================================================
log:
  level: debug
  #dir: ./log
  pretty: true
  #default: true

# ==============================================================================
# H e a l t h
# ==============================================================================
health:
  prettyPrint: true

# ==============================================================================
# M a i l s e r v e r
# ==============================================================================
mail:
  #activated: false
  host: localhost
  port: 5025
  log: false

