name: 💡 Authentication Service Feature Request
description: Suggest a new feature or enhancement for the Authentication microservice
labels: [enhancement, auth]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your idea! Please describe clearly what you want to improve.

  - type: input
    id: title
    attributes:
      label: Feature title
      placeholder: Add MFA support for Keycloak users
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature description
      placeholder: Describe what the feature should do and why it's useful.
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale / Motivation
      placeholder: Explain the benefit or use case for this feature.
    validations:
      required: true
