name: 🐛 Authentication Service Bug Report
description: Report a reproducible issue or unexpected behavior in the Authentication microservice
labels: [bug, auth, needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please include as much detail as possible.

  - type: input
    id: summary
    attributes:
      label: Bug summary
      description: What went wrong?
      placeholder: Login mutation fails with 400 error...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the bug?
      placeholder: |
        1. Start the auth-service with `pnpm run start:dev`
        2. Send a login mutation via GraphQL
        3. Observe error response
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: Login mutation should return a valid access token.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or screenshots
      description: Paste logs or attach screenshots (omit secrets).
      render: shell
    validations:
      required: false

  - type: dropdown
    id: env
    attributes:
      label: Environment
      options:
        - Local Development
        - Docker Compose
        - Production Deployment
    validations:
      required: true
