name: 🔒 Security Vulnerability Report
description: Report a potential security vulnerability in the Omnixys Authentication Service
labels: [security, urgent, auth]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Security Notice**: Please avoid sharing sensitive information publicly.
        Use this form to responsibly disclose vulnerabilities in the Authentication microservice.

  - type: input
    id: title
    attributes:
      label: Vulnerability summary
      placeholder: e.g., Token refresh endpoint allows replay attacks
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Describe the vulnerability in detail and its potential impact.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      placeholder: Explain how to reproduce the issue if possible.
    validations:
      required: false

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested mitigation
      placeholder: Provide any ideas on how to fix or mitigate the issue.
    validations:
      required: false
