name: 🔐 Security Vulnerability
description: Vertrauliche Meldung einer Sicherheitslücke
labels: [security, confidential]
body:
  - type: markdown
    attributes:
      value: |
        Bitte **öffentliche Details vermeiden**. Du kannst diese Vorlage ausfüllen und an [security@omnixys.com](mailto:security@omnixys.com) senden oder dieses Issue direkt erstellen (wird vom Core-Team vertraulich behandelt).

  - type: input
    id: title
    attributes:
      label: Betroffener Bereich / Titel
      placeholder: z. B. "Fehlende Authentifizierung bei Invoice-API"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Beschreibung des Problems
      placeholder: |
        - Unautorisierter Zugriff auf bestimmte Endpunkte möglich
        - Reproduzierbar durch Curl-Call mit ...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Schritte zur Reproduktion
      description: Wie lässt sich das Verhalten nachvollziehen?
      render: shell
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: CVSS-Schweregrad (falls bekannt)
      options:
        - Critical (CVSS 9.0–10)
        - High (CVSS 7.0–8.9)
        - Medium (CVSS 4.0–6.9)
        - Low (CVSS 0.1–3.9)
        - Unklar
