 # @license GPL-3.0-or-later
 # Copyright (C) 2025 Caleb Gyamfi - Omnixys Technologies
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 # See the GNU General Public License for more details.
 #
 # For more information, visit <https://www.gnu.org/licenses/>.

name: ✅ Task
description: Create a new task or to-do for the Authentication Service project
title: "[Auth Task] "
labels: [task, auth]
body:
  - type: input
    id: title
    attributes:
      label: Task summary
      placeholder: e.g., Refactor Keycloak service logging
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Task details
      placeholder: Describe the task, its goal, and expected deliverables.
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
