name: ✅ Task
description: Create a new task or to-do for the Authentication Service project
labels: [task, auth]
body:
  - type: input
    id: title
    attributes:
      label: Task summary
      placeholder: e.g., Refactor Keycloak service logging
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Task details
      placeholder: Describe the task, its goal, and expected deliverables.
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
