spring:
  profiles:
    active: "identity,operate,tasklist,broker,consolidated-auth"

management:
  server:
    port: 9600
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,configprops
  endpoint:
    configprops:
      show-values: ALWAYS

server:
  forward-headers-strategy: none
  address: 0.0.0.0

zeebe:
  host: 0.0.0.0
  log:
    level: "info"

  broker:
    # zeebe.broker.gateway
    gateway:
      enable: true
      network:
        host: 0.0.0.0
        port: 26500

    # zeebe.broker.network
    network:
      host: 0.0.0.0
      commandApi:
        port: 26501
      internalApi:
        port: 26502

    # zeebe.broker.data
    data:
      snapshotPeriod: 5m
      # Allow running with low disk space (for local development)
      diskUsageCommandWatermark: 0.998
      diskUsageReplicationWatermark: 0.999
      freeSpace:
        processing: 2GB
        replication: 3GB

    # zeebe.broker.threads
    threads:
      cpuThreadCount: "3"
      ioThreadCount: "3"

    # zeebe.broker.exporters
    exporters:
      elasticsearch:
        className: "io.camunda.zeebe.exporter.ElasticsearchExporter"
        args:
          url: "http://elasticsearch:9200"
          # Default is 1000, reduced to 1 for faster local development feedback
          bulk:
            size: 1
          index:
            prefix: "zeebe-record"
      CamundaExporter:
        className: "io.camunda.exporter.CamundaExporter"
        args:
          connect:
            type: elasticsearch
            url: "http://elasticsearch:9200"
          createSchema: true

camunda:
  persistent:
    sessions:
      enabled: true

  rest:
    query:
      enabled: true

  security:
    authentication:
      method: "oidc"
      unprotectedApi: false
    authorizations:
      enabled: true
    initialization:
      defaultRoles:
        admin:
          users:
            - demo
          clients:
            - orchestration
        connectors:
          users:
            - connectors
          clients:
            - connectors

  database:
    index:
      numberOfReplicas: 0
  data:
    secondary-storage:
      type: elasticsearch
      elasticsearch:
        url: "http://elasticsearch:9200"

  operate:
    persistentSessionsEnabled: true
    identity:
      redirectRootUrl: "http://localhost:8088/operate"

  tasklist:
    identity:
      redirectRootUrl: "http://localhost:8088/tasklist"

