 # @license GPL-3.0-or-later
 # Copyright (C) 2025 Caleb Gyamfi - Omnixys Technologies
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 # See the GNU General Public License for more details.
 #
 # For more information, visit <https://www.gnu.org/licenses/>.
 
name: Daily OWASP Dependency Check – Omnixys Authentication Service

on:
  schedule:
    - cron: '0 2 * * *'  # täglich um 2 Uhr nachts (UTC)
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install OWASP Dependency-Check
        run: |
            curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip -o dependency-check-12.1.0-release.zip
            unzip dependency-check-12.1.0-release.zip -d dependency-check
            chmod +x dependency-check/dependency-check

      - name: Run OWASP Dependency Check
        run: |
          dependency-check/dependency-check/bin/dependency-check.sh \
            --project "Omnixys Authentication Service" \
            --scan . \
            --nvdApiKey ${{ secrets.NVD_API_KEY }} \
            --format "HTML" \
            --out dependency-check-report
        continue-on-error: true

      - name: Upload Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-report
          path: ./dependency-check-report/*.html
