name: Dependency Check – Authentication

on:
  workflow_dispatch: # Manuelles Auslösen
  schedule:
    - cron: '0 12 * * 1' # Jeden Montag um 12:00 Uhr UTC

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.10.0]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: ⚙️ Enable Corepack (pnpm)
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # --- Fix: mkdir separat + Fehler tolerant behandeln ---
      - name: Create reports directory
        run: mkdir -p reports

      - name: Run pnpm audit
        run: |
          pnpm audit --json > reports/audit-report.json || true
          jq '.' reports/audit-report.json > reports/audit-report-pretty.json || true

      - name: Check outdated packages
        run: |
          pnpm outdated --json > reports/outdated.json || true
          jq '.' reports/outdated.json > reports/outdated-pretty.json || true

      # Optional: Zusammenfassung im Joblog (nützlich in CI)
      - name: Print vulnerability summary
        run: |
          echo "## Dependency Audit Summary" >> $GITHUB_STEP_SUMMARY
          if jq -e '.metadata.vulnerabilities.moderate > 0 or .metadata.vulnerabilities.high > 0 or .metadata.vulnerabilities.critical > 0' reports/audit-report.json > /dev/null; then
            echo "⚠️ Vulnerabilities detected! Check audit-report.json for details." >> $GITHUB_STEP_SUMMARY
            jq -r '.advisories | to_entries[] | "\(.value.module_name): \(.value.recommendation)"' reports/audit-report.json >> $GITHUB_STEP_SUMMARY || true
          else
            echo "✅ No vulnerabilities found." >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: node-dependency-reports
          path: reports/
