 # @license GPL-3.0-or-later
 # Copyright (C) 2025 Caleb Gyamfi - Omnixys Technologies
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 # See the GNU General Public License for more details.
 #
 # For more information, visit <https://www.gnu.org/licenses/>.
 
name: 🔄 Update Dependency Management Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-dependency-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "omnixys-bot"
          git config user.email "bot@omnixys.com"

      - name: Generate docs/dependency-management.md
        run: |
          mkdir -p docs
          cat <<'EOF' > docs/dependency-management.md
          # 📦 Dependency Management in Omnixys Authentication Service

          Dieses Dokument beschreibt, wie Abhängigkeiten im `omnixys-${{ secrets.SERVICE }}-service` mit [Dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates) und GitHub Actions verwaltet werden.

          ...

          © 2025 Omnixys – Modular Thinking. Infinite Possibilities.
          EOF

      - name: Commit and Push if Changed
        run: |
          git add docs/dependency-management.md
          git diff --quiet && echo "No changes." || (
            git commit -m "docs: update dependency-management.md [automated]"
            git push
          )
